# Generated by Django 4.2.4 on 2023-08-29 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='movie_photos/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='movie_video/%Y/%m/%d')),
                ('slug', models.SlugField()),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('data_release', models.IntegerField()),
                ('world_rating', models.FloatField(blank=True, null=True)),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('rating_mpaa', models.CharField(choices=[('G', 'Рейтинг G — Нет возрастных ограничений'), ('PG', 'Рейтинг PG — Рекомендуется присутствие родителей'), ('PG13', 'Рейтинг PG-13 — Детям до 13 лет просмотр не желателен'), ('R', 'Рейтинг R — Лицам до 17 лет обязательно присутствие взрослого'), ('NC17', 'Рейтинг NC-17 — Лицам до 18 лет просмотр запрещен')], max_length=4)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie_app.country')),
                ('genre', models.ManyToManyField(to='movie_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='rewards_photo/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='TypePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField()),
                ('date_review', models.DateField()),
                ('user_rating', models.FloatField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
                ('user', models.ForeignKey(default='Пользователь удален', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], max_length=1)),
                ('description', models.TextField()),
                ('date_born', models.DateField()),
                ('place_born', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='person_photo/%Y/%m/%d')),
                ('slug', models.SlugField(default='')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie_app.genre')),
                ('type_person', models.ManyToManyField(to='movie_app.typeperson')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(to='movie_app.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rewards',
            field=models.ManyToManyField(to='movie_app.reward'),
        ),
    ]
