# Generated by Django 4.2.4 on 2023-08-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='reward',
            name='slug',
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='person',
            name='genre',
        ),
        migrations.AddField(
            model_name='person',
            name='genre',
            field=models.ManyToManyField(to='movie_app.genre'),
        ),
    ]
