# Generated by Django 4.2.4 on 2023-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_options_reward_slug_remove_person_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rewards',
            field=models.ManyToManyField(blank=True, null=True, to='movie_app.reward'),
        ),
    ]
